//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURSOS()
        {
            this.CURSOS_PROFES = new HashSet<CURSOS_PROFES>();
            this.NOTAS_ESTUDIANTES = new HashSet<NOTAS_ESTUDIANTES>();
        }
    
        public int ID_CURSO { get; set; }
        public string DESC_CURSO { get; set; }
        public int ID_CARRERA { get; set; }
    
        public virtual CARRERAS CARRERAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CURSOS_PROFES> CURSOS_PROFES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS_ESTUDIANTES> NOTAS_ESTUDIANTES { get; set; }
    }
}
