//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSOS_PROFES
    {
        public int ID_CURSO_PROFE { get; set; }
        public int ID_CURSO { get; set; }
        public int ID_PROFESOR { get; set; }
        public string ESTADO { get; set; }
    
        public virtual CURSOS CURSOS { get; set; }
        public virtual PROFESORES PROFESORES { get; set; }
    }
}
