//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTUDIANTES()
        {
            this.NOTAS_ESTUDIANTES = new HashSet<NOTAS_ESTUDIANTES>();
        }
    
        public int ID_ESTUDIANTE { get; set; }
        public string IDENTIFICACION_EST { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string GENERO { get; set; }
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS_ESTUDIANTES> NOTAS_ESTUDIANTES { get; set; }
    }
}
