//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MODELO_DATOS_UAMEntities : DbContext
    {
        public MODELO_DATOS_UAMEntities()
            : base("name=MODELO_DATOS_UAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARRERAS> CARRERAS { get; set; }
        public virtual DbSet<CURSOS> CURSOS { get; set; }
        public virtual DbSet<CURSOS_PROFES> CURSOS_PROFES { get; set; }
        public virtual DbSet<ESTUDIANTES> ESTUDIANTES { get; set; }
        public virtual DbSet<NOTAS_ESTUDIANTES> NOTAS_ESTUDIANTES { get; set; }
        public virtual DbSet<PROFESORES> PROFESORES { get; set; }
    }
}
