//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTAS_ESTUDIANTES
    {
        public int ID_NOTA_ESTUDIANTE { get; set; }
        public int ID_ESTUDIANTE { get; set; }
        public int ID_CURSO { get; set; }
        public decimal NOTA { get; set; }
    
        public virtual CURSOS CURSOS { get; set; }
        public virtual ESTUDIANTES ESTUDIANTES { get; set; }
    }
}
