//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFESORES()
        {
            this.CURSOS_PROFES = new HashSet<CURSOS_PROFES>();
        }
    
        public int ID_PROFESOR { get; set; }
        public string IDENTIFICACION_PROF { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CURSOS_PROFES> CURSOS_PROFES { get; set; }
    }
}
